"""empty message

Revision ID: 0b7f352c91ee
Revises: 4b67927c17ee
Create Date: 2025-02-14 00:06:05.078228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7f352c91ee'
down_revision = '4b67927c17ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=15), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=50), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=False),
    sa.Column('patient_sex', sa.String(length=10), nullable=False),
    sa.Column('cc', sa.String(length=255), nullable=True),
    sa.Column('bp', sa.String(length=20), nullable=True),
    sa.Column('pulse', sa.String(length=20), nullable=True),
    sa.Column('temp', sa.String(length=20), nullable=True),
    sa.Column('spo', sa.String(length=20), nullable=True),
    sa.Column('inv', sa.String(length=255), nullable=True),
    sa.Column('rx', sa.Text(), nullable=False),
    sa.Column('advice', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['registration.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription')
    # ### end Alembic commands ###
