"""empty message

Revision ID: 16ca0ae3a52b
Revises: 0b7f352c91ee
Create Date: 2025-02-16 23:24:27.998190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ca0ae3a52b'
down_revision = '0b7f352c91ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
