"""empty message

Revision ID: cfb2e1fdcd67
Revises: 
Create Date: 2025-02-10 21:24:32.637931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb2e1fdcd67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('profile_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('achievement', sa.String(length=255), nullable=False),
    sa.Column('college', sa.String(length=150), nullable=False),
    sa.Column('higher_degree', sa.String(length=225), nullable=True),
    sa.Column('course', sa.String(length=225), nullable=True),
    sa.Column('extra', sa.String(length=225), nullable=True),
    sa.Column('current_position', sa.String(length=100), nullable=False),
    sa.Column('govt_reg', sa.String(length=100), nullable=False),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['registration.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_info')
    op.drop_table('registration')
    # ### end Alembic commands ###
